### ISSUE TITLE
Avatars converted to glTF and multi-users example on the web

### ISSUE THREAD

**Issue by vincentfretin** [xrtlab/Validated-Avatar-Library-for-Inclusion-and-Diversity---VALID#1]
Thank you for making those avatars available with a MIT license!

I wrote a multi-users example with [A-Frame](https://aframe.io) (that's using [threejs](https://threejs.org/)) and [networked-aframe](https://github.com/networked-aframe/networked-aframe) with a UI to select the avatar and I added an idle and walking animations on those avatars, you can see yourself in a mirror.
Demo: https://naf-valid-avatars.glitch.me/
GitHub: https://github.com/networked-aframe/naf-valid-avatars

To be able to use those avatars I converted in https://github.com/c-frame/valid-avatars-glb the 200 avatars from fbx to glb with blender and gltf-transform optimize with meshopt compression reducing the size by two (see scripts folder in the repo if you're curious), and also extracted all images from the pdf and produced a json file with all the avatars and path to the image and glb.

Some mistakes I found in your pdf:
- MENA_1_Casual missing the gender, should be MENA_M_1_Casual
- Mena instead of MENA on some texts
- x_ instead of X_ on some texts
- There are images for X_AIAN_F_2_* but the following fbx files don't exist in the repo:
  X_Non-validated/X_AIAN_F_2_Casual.fbx
  X_Non-validated/X_AIAN_F_2_Busi.fbx
  X_Non-validated/X_AIAN_F_2_Medi.fbx
  X_Non-validated/X_AIAN_F_2_Milit.fbx
  X_Non-validated/X_AIAN_F_2_Util.fbx
  
If you do other avatars in the future, please consider putting all the images in a folder with the same name as the fbx file, that would be awesome.

**Comment by Zyrcant** [comment]
Wow, thanks for the demo!! That is super cool. I'll link your repo in the Readme to signal boost it :-) 

Thanks for pointing out the typos in the pdf (The AIAN avatar should be F_1 instead of F_2). I went ahead and fixed all typos.
